apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: neshc
    meta.helm.sh/release-namespace: cran2testing
  generation: 1
  labels:
    app.kubernetes.io/instance: neshc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: healing-controller
    app.kubernetes.io/version: "1.0"
    healing-controller.rcpha/restart: exclude
    helm.sh/chart: healing-controller-7.11.3
  name: nes-healing-controller
  namespace: cran2testing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: neshc
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: healing-controller
      app.kubernetes.io/version: "1.0"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: neshc
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: healing-controller
        app.kubernetes.io/version: "1.0"
        healing-controller.rcpha/restart: exclude
    spec:
      affinity: {}
      containers:
        - args:
            - app.py
          command:
            - python
          image: quay.io/gmeghnag/reproducer:03441587
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /probe/liveness
              port: 50056
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: nes-healing-controller
          ports:
            - containerPort: 50056
              protocol: TCP
            - containerPort: 50057
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seLinuxOptions:
              level: s0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 9999
        runAsGroup: 9999
        runAsUser: 9999
        sysctls:
          - name: net.ipv4.ip_local_port_range
            value: 54000 65535
      serviceAccount: healing-controller
      serviceAccountName: healing-controller
      terminationGracePeriodSeconds: 30
