apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: neshc
    meta.helm.sh/release-namespace: cran2
  labels:
    app.kubernetes.io/instance: neshc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: healing-controller
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: healing-controller-7.11.3
  name: healing-controller
  namespace: cran2
spec:
  clusterIP: 172.30.154.138
  clusterIPs:
    - 172.30.154.138
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: restful-api
      port: 50056
      protocol: TCP
      targetPort: 50056
    - name: grpc-server
      port: 50057
      protocol: TCP
      targetPort: 50057
  selector:
    app.kubernetes.io/instance: neshc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: healing-controller
    app.kubernetes.io/version: "1.0"
  sessionAffinity: None
  type: ClusterIP
